version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx
#    networks:
#        - app-network

  mysql-app:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
          MYSQL_DATABASE: customers
          MYSQL_ROOT_PASSWORD: root
#    networks:
#      - app-network
    volumes:
      - $HOME/Documents/dbdata:/var/lib/mysql

#networks:
#  app-network:
#    driver: bridge

